### PR TITLE
emit error when secure connection fails before initializeStream()

### LINKED ISSUE #66: unrecognized error in addSecureConnection
Hi guys, 
i think [here](https://github.com/phergie/phergie-irc-client-react/blob/master/src/Client.php#L681) can be added some error handling/logging. Something like ```function ($e) { $this->logger->error($e->getMessage()); }``` can be very useful. 

Currently i was not able detect problem with SecureConnector (in my case `"Unable to complete SSL/TLS handshake: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed"`. 

Thank your for your time, nice project!

### PR DESCRIPTION
**Pull request by 1dal**
Fixes #66

### CODE REVIEW

**Comment by 1dal** [comment]
Thank you guys

**Comment by elazar** [comment]
@svpernova09 This still needs merging?

**Comment by 1dal** [comment]
Thx

**Pull request merged**
