### PR TITLE
Updated to the latest ReactPHP versions

### PR DESCRIPTION
**Pull request by WyriHaximus**
- [X] Update Packages in composer.json
- [X] Update Client
- [x] Update ReadStream
- [x] Update WriteStream
- [x] Test in project
- [x] Try to support older versions as well 

Note that this is a work in progress, I'll update the tile once it's ready for review.

### CODE REVIEW

**Comment by matthewtrask** [comment]
This is awesome!

**Comment by WyriHaximus** [comment]
@matthewtrask thanks! There has been some great improvements since the versions used in this package. It's time to update :tada:

**Comment by WyriHaximus** [comment]
Essentially this PR Is done @elazar @matthewtrask @svpernova09 but @elazar mentioned some bigger changes on IRC. Do we want that in this PR as well, or should I create a followup with those changes?

**Comment by elazar** [comment]
I'd say this is fine as-is. Bigger changes can wait for a followup PR.

**Comment by WyriHaximus** [comment]
Sounds good to me, will try and sort backwards compatible tomorrow 👍

**Comment by WyriHaximus** [comment]
Updated the PR so it supports all the currently supported react/stream versions

**Comment by WyriHaximus** [comment]
:tada:

**Pull request merged**
